#ShrinavLoka 
#FaceCreator
#The purpose of this code is to create a face using shapes with circles as eyes, a square as a mouth, and a hexagon as the face shape
#imports turtle
import turtle as trtl
#creates turtle object
painter = trtl.Turtle()
#goes back to put align the face
painter.right(180)
painter.forward(50)
painter.right(180)
#creates square/mouth
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
#creates right eye
painter.left(90)
painter.forward(100)
painter.circle(50)
#creates left eye
painter.right(180)
painter.forward(100)
painter.left(90)
painter.forward(100)
painter.penup()
painter.forward(100)
painter.left(90)
painter.forward(100)
painter.pendown()
painter.circle(50)
painter.penup()
painter.left(180)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
#creates face shape
painter.pendown()
painter.forward(100)
painter.left(180)
painter.forward(100)
painter.right(90)
painter.forward(50)
painter.right(90)
painter.forward(350)
painter.left(120)
painter.forward(300)
painter.left(60)
painter.forward(300)
painter.left(60)
painter.forward(300)
painter.left(60)
painter.forward(300)
painter.left(60)
painter.forward(300)
painter.left(60)
painter.forward(300)
wn = trtl.Screen()
wn.mainloop()
