#Shrinav Loka

#ProjectPlanningAPicture

#The purpose of my program is to use 5 different turtle methods, create 5 different shapes, and use a color method. I am planning to use the methods pencolor(), circle(), forward(), left(), and goto(x, y). I am planning to create a human using circle, square, triangle, rectangle, and star shapes

#imports turtle
import turtle as trtl
#creates turtle object painter
painter = trtl.Turtle()
#asks user for the radius of the head
x = int(input("What do you want the radius of the head to be? "))
#Asks the user for the body color
y = input("What do you want the color of the hat to be? ")
#creating a head using a circle
painter.circle(x)
d=2*x
#creating a body using a square
painter.forward(d)
painter.right(90)
painter.forward(2*d)
painter.right(90)
painter.forward(2*d)
painter.right(90)
painter.forward(2*d)
painter.right(90)
painter.forward(d)
#creating limbs in the shape of rectangles
painter.forward(1.5*d)
painter.right(90)
painter.forward(2*d)
painter.right(90)
painter.forward(1.5*d)
painter.forward(1.5*d)
painter.right(90)
painter.forward(2*d)
painter.right(90)
painter.forward(.5*d)
painter.right(90)
painter.forward(4*d)
painter.left(90)
painter.forward(.75*d)
painter.left(90)
painter.forward(2*d)
painter.right(90)
painter.forward(.5*d)
painter.right(90)
painter.forward(2*d)
painter.left(90)
painter.forward(.75*d)
painter.left(90)
painter.forward(4*d)
#creating a hat us using a triangle
painter.penup()
painter.left(90)
painter.forward(x)
painter.right(90)
painter.forward(1.75*x)
painter.pendown()
painter.left(330)
painter.fillcolor(y)
painter.begin_fill()
painter.circle(1.25*x,360,3)
painter.end_fill()
painter.penup()
painter.right(15)
#creating a star in the sky using the .circle method. 
painter.goto(400,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(300,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(250,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(200,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(150,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(100,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(50,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(0,325)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-50,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-100,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-150,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-200,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-250,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-300,350)
painter.pendown()
painter.circle(12.5,720,5)
painter.penup()
painter.goto(-350,350)
painter.pendown()
painter.circle(12.5,720,5)
wn = trtl.Screen()
wn.mainloop()
